CREATE TABLE SK_ACTION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(64) NOT NULL,
	DIALOGHTML VARCHAR(4098),
	EXECUTEJS VARCHAR(4098)
);

ALTER TABLE SK_ACTION ADD UNIQUE INDEX ACT_NAME_IDX(NAME ASC);

CREATE TABLE SK_GROUP ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(16)
);

ALTER TABLE SK_GROUP ADD UNIQUE INDEX GRP_NAME_IDX(NAME ASC);

CREATE TABLE SK_TEMPLATE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	CONTENT VARCHAR(4098),
	ACTION_ID INT NOT NULL,
	FOREIGN KEY(ACTION_ID) REFERENCES SK_ACTION(ID)
);

CREATE TABLE SK_RESOURCE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	CONTENT BLOB,
	ACTION_ID INT NOT NULL,
	FOREIGN KEY(ACTION_ID) REFERENCES SK_ACTION(ID)
);

CREATE TABLE SK_ACTION_GROUP (
	ACTION_ID INT NOT NULL,
	GROUP_ID INT NOT NULL,
	FOREIGN KEY(ACTION_ID) REFERENCES SK_ACTION(ID),
	FOREIGN KEY(GROUP_ID) REFERENCES SK_GROUP(ID)
);

CREATE TABLE SK_FRAGMENT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(24),
	FRAGMENT VARCHAR(4098)
);



